#!/bin/bash

# cd to the script directory
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

set -xe

vagrant box remove basenode
rm basenode.old || echo "Old basenode was not deleted"
mv basenode basenode.old || echo "Nothing to move"
vagrant package --output basenode
